services:
  frontend:
    build: C:/Users/HP/Desktop/DecentraTeach/client
    ports:
      - "5173:5173"
    networks:
      - mern
  
  backend:
    build: C:/Users/HP/Desktop/DecentraTeach/server
    ports:
      - "5000:5000"
    networks:
      - mern
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local
    
